var nodeData = [
  {
    "id": "P042",
    "Province": "al-Fayyūm",
    "VillageEN": "al-Ḥanbūshīya",
    "Y": 100,
    "Feddans": 59,
    "Ibra": 175,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1170,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P043",
    "Province": "al-Fayyūm",
    "VillageEN": "ar-Rūbīyīn",
    "Y": 100,
    "Feddans": 79,
    "Ibra": 235,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1171,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P044",
    "Province": "al-Fayyūm",
    "VillageEN": "al-Ghāba",
    "Y": 100,
    "Feddans": 10,
    "Ibra": 10,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1172,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P045",
    "Province": "al-Bahnasā",
    "VillageEN": "Dahmarū",
    "Y": 100,
    "Feddans": 10,
    "Ibra": 10,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1174,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P046",
    "Province": "al-Minūfīya",
    "VillageEN": "al-Khirba",
    "Y": 100,
    "Feddans": 970,
    "Ibra": 2000,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1175,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P047",
    "Province": "al-Gīza",
    "VillageEN": "Abū Fār",
    "Y": 100,
    "Feddans": 230,
    "Ibra": 1200,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1176,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P048",
    "Province": "al-Bahnasā",
    "VillageEN": "Daḥṭūṭ al-Ḥigāra",
    "Y": 100,
    "Feddans": 1680,
    "Ibra": 8000,
    "Founder": "Musa ibn al-Lamti",
    "FoundationYear": 1180,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P049",
    "Province": "al-Fayyūm",
    "VillageEN": "al-Aʿlām",
    "Y": 100,
    "Feddans": 94,
    "Ibra": 281,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1180,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P050",
    "Province": "al-Fayyūm",
    "VillageEN": "Shūbays ?",
    "Y": 100,
    "Feddans": 10,
    "Ibra": 10,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1181,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P051",
    "Province": "al-Qūṣīya",
    "VillageEN": "Naqqāda",
    "Y": 100,
    "Feddans": 6667,
    "Ibra": 20000,
    "Founder": "Ṣalāḥ al-Dīn",
    "FoundationYear": 1182,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P052",
    "Province": "al-Buḥayra",
    "VillageEN": "Asknīda",
    "Y": 100,
    "Feddans": 1437,
    "Ibra": 2500,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1244,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P053",
    "Province": "al-Buḥayra",
    "VillageEN": "al-Khammārat Dakdūka",
    "Y": 100,
    "Feddans": 418,
    "Ibra": 1860,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1244.5,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P054",
    "Province": "al-Buḥayra",
    "VillageEN": "Safṭ Qulayshān",
    "Y": 100,
    "Feddans": 1014,
    "Ibra": 3000,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1245,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P055",
    "Province": "al-Gīza",
    "VillageEN": "Bāṭin Gabrā",
    "Y": 100,
    "Feddans": 839,
    "Ibra": 2517,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1245.5,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P056",
    "Province": "al-Gīza",
    "VillageEN": "Gazīrat Bāṭin Gabrā",
    "Y": 100,
    "Feddans": 10,
    "Ibra": 10,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1246,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P057",
    "Province": "al-Gīza",
    "VillageEN": "Gazāʾir Badsā",
    "Y": 100,
    "Feddans": 700,
    "Ibra": 2100,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1246.5,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P058",
    "Province": "al-Gīza",
    "VillageEN": "Gazīrat Barnasht",
    "Y": 100,
    "Feddans": 400,
    "Ibra": 1200,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1247,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P059",
    "Province": "ash-Sharqīya",
    "VillageEN": "Dahmasā al-Ḥamām",
    "Y": 100,
    "Feddans": 2652,
    "Ibra": 10000,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1247.5,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P060",
    "Province": "ash-Sharqīya",
    "VillageEN": "Mubāshir",
    "Y": 100,
    "Feddans": 2842,
    "Ibra": 3600,
    "Founder": "Sultan Negm al-Din",
    "FoundationYear": 1248,
    "Category": 1,
    "type": "Ayyubid"
  },
  {
    "id": "P061",
    "Province": "Ḍawāḥī al-Qāhira",
    "VillageEN": "Birkat al-Fīl",
    "Y": 100,
    "Feddans": 10,
    "Ibra": 10,
    "Founder": "Sultan al-Ẓāhir Baybars",
    "FoundationYear": 1267,
    "Category": 3,
    "type": "Non-Qalawunid Sultan"
  },
  {
    "id": "P062",
    "Province": "al-Ushmūnayn",
    "VillageEN": "Miʿṣarat Ibn Barghash",
    "Y": 100,
    "Feddans": 366,
    "Ibra": 2500,
    "Founder": "Sultan al-Ẓāhir Baybars",
    "FoundationYear": 1267.5,
    "Category": 3,
    "type": "Non-Qalawunid Sultan"
  },
  {
    "id": "P063",
    "Province": "al-Gīza",
    "VillageEN": "Minyat Andūna",
    "Y": 100,
    "Feddans": 10,
    "Ibra": 10,
    "Founder": "Sultan Lājīn",
    "FoundationYear": 1298,
    "Category": 3,
    "type": "Non-Qalawunid Sultan"
  },
  {
    "id": "P064",
    "Province": "al-Gīza",
    "VillageEN": "al-Mukhnān",
    "Y": 100,
    "Feddans": 620,
    "Ibra": 1860,
    "Founder": "Sultan Baybars al-Jāshankīr",
    "FoundationYear": 1309,
    "Category": 3,
    "type": "Non-Qalawunid Sultan"
  },
  {
    "id": "P065",
    "Province": "al-Qalyūbīya",
    "VillageEN": "Munā Gaʿfar",
    "Y": 100,
    "Feddans": 1667,
    "Ibra": 5000,
    "Founder": "Sultan al-Nāṣir Muḥammad",
    "FoundationYear": 1323,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P066",
    "Province": "ash-Sharqīya",
    "VillageEN": "Khafag al-Ibil",
    "Y": 100,
    "Feddans": 708,
    "Ibra": 2000,
    "Founder": "Amir Baktamur al-Sāqī",
    "FoundationYear": 1326,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P067",
    "Province": "Aṭfīḥ",
    "VillageEN": "Ṭurā",
    "Y": 100,
    "Feddans": 226,
    "Ibra": 1000,
    "Founder": "Amir Qawṣūn",
    "FoundationYear": 1329,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P068",
    "Province": "al-Fayyūm",
    "VillageEN": "Ḥagar al-Aʿlām",
    "Y": 100,
    "Feddans": 750,
    "Ibra": 2250,
    "Founder": "Amir Qawṣūn",
    "FoundationYear": 1329,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P069",
    "Province": "al-Minūfīya",
    "VillageEN": "al-Qarīnīn",
    "Y": 100,
    "Feddans": 500,
    "Ibra": 1500,
    "Founder": "Amir Manjak al-Yusufi",
    "FoundationYear": 1349.1,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P070",
    "Province": "al-Gharbīya",
    "VillageEN": "Ḥiṣṣat Ṣandalā",
    "Y": 100,
    "Feddans": 695,
    "Ibra": 1100,
    "Founder": "Amir Manjak al-Yusufi",
    "FoundationYear": 1349.2,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P071",
    "Province": "al-Gharbīya",
    "VillageEN": "Ḥiṣṣat Qasṭa",
    "Y": 100,
    "Feddans": 190,
    "Ibra": 400,
    "Founder": "Amir Shaykhu",
    "FoundationYear": 1349.3,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P072",
    "Province": "Ibyār",
    "VillageEN": "Dalaka",
    "Y": 100,
    "Feddans": 870,
    "Ibra": 1000,
    "Founder": "Amir Uljaybugha al-Muzaffari",
    "FoundationYear": 1349.4,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P073",
    "Province": "al-Buḥayra",
    "VillageEN": "Safṭ al-Mulūk",
    "Y": 100,
    "Feddans": 1265,
    "Ibra": 1800,
    "Founder": "Amir Manjak al-Yusufi",
    "FoundationYear": 1349.5,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P074",
    "Province": "Fūwa",
    "VillageEN": "Maḥallat al-Amīr",
    "Y": 100,
    "Feddans": 500,
    "Ibra": 1500,
    "Founder": "Amir Shaykhu",
    "FoundationYear": 1349.6,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P075A",
    "Province": "al-Ushmūnayn",
    "VillageEN": "al-Wāqiya",
    "Y": 100,
    "Feddans": 200,
    "Ibra": 1000,
    "Founder": "Amir Shaykhu",
    "FoundationYear": 1349.7,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P075B",
    "Province": "al-Ushmūnayn",
    "VillageEN": "Qawārīr Banī Aḥmad",
    "Y": 100,
    "Feddans": 210,
    "Ibra": 600,
    "Founder": "Amir Shaykhu",
    "FoundationYear": 1349.75,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P076",
    "Province": "ash-Sharqīya",
    "VillageEN": "Ṭabanū",
    "Y": 100,
    "Feddans": 407,
    "Ibra": 700,
    "Founder": "Amir Shaykhu & Manjak al-Yusufi",
    "FoundationYear": 1349.8,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P077",
    "Province": "Ḍawāḥī al-Qāhira",
    "VillageEN": "Bigām",
    "Y": 100,
    "Feddans": 340,
    "Ibra": 2500,
    "Founder": "Baybugha Rus",
    "FoundationYear": 1350,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P078",
    "Province": "Ḍawāḥī al-Qāhira",
    "VillageEN": "Arāḍi al-Baʿl",
    "Y": 100,
    "Feddans": 305,
    "Ibra": 3000,
    "Founder": "Sultan as-Ṣāliḥ b. Qalāwūn",
    "FoundationYear": 1351,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P079",
    "Province": "al-Gharbīya",
    "VillageEN": "Manyal Ibn Hiwishāt",
    "Y": 100,
    "Feddans": 226,
    "Ibra": 1000,
    "Founder": "Amir Manklibugha al-Fakhri",
    "FoundationYear": 1353,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P080",
    "Province": "ad-Daqahliyā & al-Murtāḥīya",
    "VillageEN": "Minyat Bizwā",
    "Y": 100,
    "Feddans": 816,
    "Ibra": 3500,
    "Founder": "Amir Uzdamur al-Khazindar",
    "FoundationYear": 1355,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P081",
    "Province": "Ḍawāḥī al-Qāhira",
    "VillageEN": "Minyat Ḥalfā",
    "Y": 100,
    "Feddans": 1167,
    "Ibra": 3500,
    "Founder": "Amir Sarghatmish an-Nasiri",
    "FoundationYear": 1355.5,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P082",
    "Province": "Ḍawāḥī al-Qāhira",
    "VillageEN": "Minyat Ṣurud",
    "Y": 100,
    "Feddans": 410,
    "Ibra": 4500,
    "Founder": "Sultan al-Nasir Hasan",
    "FoundationYear": 1359.25,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P083",
    "Province": "al-Qalyūbīya",
    "VillageEN": "Qahā",
    "Y": 100,
    "Feddans": 2743,
    "Ibra": 8000,
    "Founder": "Sultan al-Nasir Hasan",
    "FoundationYear": 1359.5,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P084",
    "Province": "al-Gharbīya",
    "VillageEN": "Maḥallat al-Khādim",
    "Y": 100,
    "Feddans": 1000,
    "Ibra": 3000,
    "Founder": "Sultan al-Nasir Hasan",
    "FoundationYear": 1359.75,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P085",
    "Province": "ad-Daqahliyā & al-Murtāḥīya",
    "VillageEN": "Bārinbāra",
    "Y": 100,
    "Feddans": 1704,
    "Ibra": 1000,
    "Founder": "Yalbugha al-ʿUmari",
    "FoundationYear": 1360,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P086",
    "Province": "al-Ushmūnayn",
    "VillageEN": "Abū Qurqās",
    "Y": 100,
    "Feddans": 1716,
    "Ibra": 5000,
    "Founder": "Amir Taybugha al-Tawil",
    "FoundationYear": 1366,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P087",
    "Province": "al-Qalyūbīya",
    "VillageEN": "Kōm as-Samn",
    "Y": 100,
    "Feddans": 628,
    "Ibra": 1884,
    "Founder": "Amir Uljay al-Yusufi",
    "FoundationYear": 1368.25,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P088",
    "Province": "al-Gharbīya",
    "VillageEN": "Safṭ Abī Turāb",
    "Y": 100,
    "Feddans": 4908,
    "Ibra": 20000,
    "Founder": "Khawand Baraka",
    "FoundationYear": 1370,
    "Category": 5,
    "type": "Qalawunid Family"
  },
  {
    "id": "P089",
    "Province": "ash-Sharqīya",
    "VillageEN": "Ṭaqadūs",
    "Y": 100,
    "Feddans": 1520,
    "Ibra": 6000,
    "Founder": "Khawand Baraka",
    "FoundationYear": 1370,
    "Category": 5,
    "type": "Qalawunid Family"
  },
  {
    "id": "P090",
    "Province": "al-Buḥayra",
    "VillageEN": "Sunṭays",
    "Y": 100,
    "Feddans": 2138,
    "Ibra": 3500,
    "Founder": "Sultan al-Ashraf Shaʿban",
    "FoundationYear": 1373.2,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P091",
    "Province": "Fūwa",
    "VillageEN": "Itfīna",
    "Y": 100,
    "Feddans": 734,
    "Ibra": 2200,
    "Founder": "Sultan al-Ashraf Shaʿban",
    "FoundationYear": 1373.4,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P092",
    "Province": "Fūwa",
    "VillageEN": "Gazīrat adh-Dhahab",
    "Y": 100,
    "Feddans": 400,
    "Ibra": 1200,
    "Founder": "Amir ʿUmar b. Bahadur al-Jamali",
    "FoundationYear": 1373.6,
    "Category": 4,
    "type": "Amir"
  },
  {
    "id": "P093",
    "Province": "al-Gīza",
    "VillageEN": "ʿAṭf Iṭwāb",
    "Y": 100,
    "Feddans": 1200,
    "Ibra": 5000,
    "Founder": "Sultan al-Ashraf Shaʿban",
    "FoundationYear": 1373.8,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P094",
    "Province": "al-Ushmūnayn",
    "VillageEN": "ar-Rawwāḥa",
    "Y": 100,
    "Feddans": 323,
    "Ibra": 2000,
    "Founder": "Sultan al-Ashraf Shaʿban",
    "FoundationYear": 1374,
    "Category": 2,
    "type": "Qalawunid Sultan"
  },
  {
    "id": "P095",
    "Province": "al-Bahnasā",
    "VillageEN": "Idrīga",
    "Y": 100,
    "Feddans": 2000,
    "Ibra": 6000,
    "Founder": "Amir Arghun Shah al-Ashrafi",
    "FoundationYear": 1375,
    "Category": 4,
    "type": "Amir"
  }
]
